# Generated by Django 4.0.6 on 2022-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_process', 'В обработке'), ('delivery', 'Доставляется'), ('complete', 'Завершён')], default='in_process', max_length=50, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_type', models.CharField(max_length=100, verbose_name='Вид цветка')),
                ('colour', models.CharField(choices=[('black', 'чёрный'), ('blue', 'голубой'), ('green', 'зелёный'), ('gray', 'серый'), ('olive', 'оливковый'), ('purple', 'пурпурный'), ('red', 'красный'), ('silver', 'серебристый'), ('white', 'белый'), ('yellow', 'жёлтый'), ('pink', 'розовый'), ('gold', 'золотой')], max_length=50, verbose_name='Оттенок')),
                ('availability', models.PositiveIntegerField(null=True, verbose_name='Наличие')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за шт.')),
                ('visibility', models.BooleanField(verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветы',
            },
        ),
    ]
