# Generated by Django 4.0.6 on 2022-08-01 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'verbose_name': 'Цветок', 'verbose_name_plural': 'Цветы'},
        ),
        migrations.AddField(
            model_name='flowers',
            name='visibility',
            field=models.BooleanField(blank=True, null=True, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='colour',
            field=models.CharField(choices=[('black', 'чёрный'), ('blue', 'голубой'), ('green', 'зелёный'), ('gray', 'серый'), ('olive', 'оливковый'), ('purple', 'пурпурный'), ('red', 'красный'), ('silver', 'серебристый'), ('white', 'белый'), ('yellow', 'жёлтый'), ('pink', 'розовый'), ('gold', 'золотой')], max_length=50, verbose_name='Оттенок'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена за шт.'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='seller',
            field=models.ForeignKey(default=bool, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, validators=[products.models.seller_validation], verbose_name='Продавец'),
            preserve_default=False,
        ),
    ]
