# Generated by Django 4.0.6 on 2022-08-04 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_flowers', to=settings.AUTH_USER_MODEL, validators=[products.models.seller_validation], verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_author', to=settings.AUTH_USER_MODEL, validators=[products.models.buyer_validation], verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='flowers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_flowers', to='products.flowers', verbose_name='Цветы'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_seller', to=settings.AUTH_USER_MODEL, validators=[products.models.seller_validation], verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='deals',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to=settings.AUTH_USER_MODEL, validators=[products.models.buyer_validation], verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='deals',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.dealdetails', verbose_name='Детали'),
        ),
        migrations.AddField(
            model_name='deals',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowers', through='products.DealDetails', to='products.flowers', verbose_name='Цветы'),
        ),
        migrations.AddField(
            model_name='deals',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to=settings.AUTH_USER_MODEL, validators=[products.models.seller_validation], verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='dealdetails',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='products.deals', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='dealdetails',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_flowers', to='products.flowers', validators=[products.models.visibility_validation], verbose_name='Цветы'),
        ),
    ]
