# Generated by Django 4.0.6 on 2022-08-01 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, validators=[products.models.seller_validation], verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='deals',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, validators=[products.models.buyer_validation], verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='deals',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowers', through='products.DealFlowers', to='products.flowers', verbose_name='Цветы'),
        ),
        migrations.AddField(
            model_name='dealflowers',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='products.deals', verbose_name='Цветы в заказе'),
        ),
        migrations.AddField(
            model_name='dealflowers',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_flowers', to='products.flowers', verbose_name='Цветы'),
        ),
    ]
