# Generated by Django 4.0.6 on 2022-08-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='details',
            field=models.ForeignKey(default=bool, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.dealdetails', verbose_name='Детали'),
            preserve_default=False,
        ),
    ]
