# Generated by Django 4.0.6 on 2022-08-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_deals_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='details',
        ),
    ]
