# Generated by Django 4.0.6 on 2022-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_deals_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowers', to='products.flowers', verbose_name='Цветы'),
        ),
    ]
