# Generated by Django 4.0.6 on 2022-08-02 13:53

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_dealflowers_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
        migrations.AlterField(
            model_name='deals',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowers', through='products.DealDetails', to='products.flowers', verbose_name='Цветы'),
        ),
        migrations.DeleteModel(
            name='DealFlowers',
        ),
        migrations.AddField(
            model_name='dealdetails',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='products.deals', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='dealdetails',
            name='flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_flowers', to='products.flowers', validators=[products.models.visibility_validation], verbose_name='Цветы'),
        ),
    ]
