# Generated by Django 4.0.6 on 2022-08-02 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_dealdetails_alter_deals_flowers_delete_dealflowers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(default=bool, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_author', to=settings.AUTH_USER_MODEL, validators=[products.models.buyer_validation], verbose_name='Автор отзыва'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='flowers',
            field=models.ForeignKey(default=bool, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_flowers', to='products.flowers', verbose_name='Цветы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='seller',
            field=models.ForeignKey(default=bool, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_seller', to=settings.AUTH_USER_MODEL, validators=[products.models.seller_validation], verbose_name='Продавец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.TextField(default=bool, max_length=300, verbose_name='Текст отзыва'),
            preserve_default=False,
        ),
    ]
