# Generated by Django 4.0.6 on 2022-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_deals_flowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='availability',
            field=models.PositiveIntegerField(null=True, verbose_name='Наличие'),
        ),
    ]
