# Generated by Django 4.0.6 on 2022-08-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_flowers_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество ингредиентов')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='deals',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowers', through='products.DealDetails', to='products.flowers', verbose_name='Цветы'),
        ),
        migrations.AddField(
            model_name='dealdetails',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.deals', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='dealdetails',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.flowers', verbose_name='Цветок'),
        ),
    ]
