# Generated by Django 4.0.6 on 2022-08-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_feedback_options_feedback_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='status',
            field=models.CharField(choices=[('in_process', 'В обработке'), ('delivery', 'Доставляется'), ('complete', 'Завершён')], default='in_process', max_length=50, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='flowers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_flowers', to='products.flowers', verbose_name='Цветы'),
        ),
    ]
