# Generated by Django 4.0.6 on 2022-08-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_deals_status_alter_feedback_flowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='status',
            field=models.CharField(choices=[('in_process', 'В обработке'), ('delivery', 'Доставляется'), ('complete', 'Завершён')], default='in_process', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
