# Generated by Django 4.0.6 on 2022-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_dealdetails_alter_deals_flowers_dealdetails_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdetails',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='flowers', to='products.dealdetails', verbose_name='Цветы'),
        ),
    ]
